#include <QtGlobal>

/*
   QTERMWIDGET_VERSION is (major << 16) + (minor << 8) + patch.
   can be used like #if (QTERMWIDGET_VERSION >= QT_VERSION_CHECK(0, 7, 1))
*/
#define QTERMWIDGET_VERSION      QT_VERSION_CHECK(QTERMWIDGET_VERSION_MAJOR, QTERMWIDGET_VERSION_MINOR, QTERMWIDGET_VERSION_PATCH)
