// This file was generated by dtk-settings-tools version 0.1.2 

#include <DSettings>

void GenerateSettingTranslate()
{
    auto advanced_cursor_blinkText = QObject::tr("Cursor blink");
    auto advanced_cursor_shapeName = QObject::tr("Cursor Shape");
    auto advanced_window_blur_backgroundText = QObject::tr("Blur background");
    auto basic_interface_opacityName = QObject::tr("Opacity");
    auto group_advancedName = QObject::tr("Advanced");
    auto group_advanced_cursorName = QObject::tr("Cursor");
    auto group_advanced_windowName = QObject::tr("Window");
    auto group_basicName = QObject::tr("Basic");
    auto group_basic_interfaceName = QObject::tr("Interface");
}
