// This file was generated by dtk-settings-tools version 0.1.2 

#include <DSettings>

void GenerateSettingTranslate()
{
    auto advanced_cursor_AutoCopyText = QObject::tr("AutoCopy");
    auto advanced_cursor_AutoHideText = QObject::tr("AutoHide");
    auto advanced_cursor_BlinkText = QObject::tr("Blink");
    auto advanced_cursor_ShapeName = QObject::tr("Shape");
    auto advanced_scroll_OutputtingScrollText = QObject::tr("OutputtingScroll");
    auto advanced_scroll_PressingScrollText = QObject::tr("PressingScroll");
    auto advanced_window_BlurredBackgroundText = QObject::tr("BlurredBackground");
    auto advanced_window_HideRaytheonWindowText = QObject::tr("HideRaytheonWindow");
    auto advanced_window_WindowStateName = QObject::tr("WindowState");
    auto basic_interface_FamilyName = QObject::tr("Family");
    auto basic_interface_FontSizeName = QObject::tr("FontSize");
    auto basic_interface_OpacityName = QObject::tr("Opacity");
    auto group_advancedName = QObject::tr("Advanced");
    auto group_advanced_cursorName = QObject::tr("Cursor");
    auto group_advanced_scrollName = QObject::tr("Scroll");
    auto group_advanced_windowName = QObject::tr("Window");
    auto group_basicName = QObject::tr("Basic");
    auto group_basic_interfaceName = QObject::tr("Interface");
    auto group_shortcutsName = QObject::tr("Shortcuts");
    auto group_shortcuts_advancedName = QObject::tr("Advanced");
    auto group_shortcuts_terminalName = QObject::tr("Terminal");
    auto group_shortcuts_workspaceName = QObject::tr("Workspace");
    auto shortcuts_advanced_CustomCommandName = QObject::tr("CustomCommand");
    auto shortcuts_advanced_FullScreenName = QObject::tr("FullScreen");
    auto shortcuts_advanced_RemoteManagerName = QObject::tr("RemoteManager");
    auto shortcuts_advanced_RenameTabName = QObject::tr("RenameTab");
    auto shortcuts_advanced_ShowShortCutName = QObject::tr("ShowShortCut");
    auto shortcuts_terminal_CopyName = QObject::tr("Copy");
    auto shortcuts_terminal_DefaultSizeName = QObject::tr("DefaultSize");
    auto shortcuts_terminal_PasteName = QObject::tr("Paste");
    auto shortcuts_terminal_SearchName = QObject::tr("Search");
    auto shortcuts_terminal_SelectAllName = QObject::tr("SelectAll");
    auto shortcuts_terminal_SkipToNextCommandName = QObject::tr("SkipToNextCommand");
    auto shortcuts_terminal_SkipToPreCommandName = QObject::tr("SkipToPreCommand");
    auto shortcuts_terminal_ZoomInName = QObject::tr("ZoomIn");
    auto shortcuts_terminal_ZoomOutName = QObject::tr("ZoomOut");
    auto shortcuts_workspace_CloseOtherWindowsName = QObject::tr("CloseOtherWindows");
    auto shortcuts_workspace_CloseWindowName = QObject::tr("CloseWindow");
    auto shortcuts_workspace_CloseWorkspaceName = QObject::tr("CloseWorkspace");
    auto shortcuts_workspace_FocusNavDownName = QObject::tr("FocusNavDown");
    auto shortcuts_workspace_FocusNavLeftName = QObject::tr("FocusNavLeft");
    auto shortcuts_workspace_FocusNavRightName = QObject::tr("FocusNavRight");
    auto shortcuts_workspace_FocusNavUpName = QObject::tr("FocusNavUp");
    auto shortcuts_workspace_HorizontalSplitName = QObject::tr("HorizontalSplit");
    auto shortcuts_workspace_NewWorkspaceName = QObject::tr("NewWorkspace");
    auto shortcuts_workspace_NextWorkspaceName = QObject::tr("NextWorkspace");
    auto shortcuts_workspace_PreWorkspaceName = QObject::tr("PreWorkspace");
    auto shortcuts_workspace_VerticalSplitName = QObject::tr("VerticalSplit");
}
