// This file was generated by dtk-settings-tools version 0.1.2 

#include <DSettings>

void GenerateSettingTranslate()
{
    auto advanced_cursor_blinkText = QObject::tr("Cursor blink");
    auto advanced_cursor_shapeName = QObject::tr("Cursor Shape");
    auto advanced_window_blur_backgroundText = QObject::tr("Blur background");
    auto basic_interface_opacityName = QObject::tr("Opacity");
    auto group_advancedName = QObject::tr("Advanced");
    auto group_advanced_cursorName = QObject::tr("Cursor");
    auto group_advanced_windowName = QObject::tr("Window");
    auto group_basicName = QObject::tr("Basic");
    auto group_basic_interfaceName = QObject::tr("Interface");
    auto group_shortcutsName = QObject::tr("Shortcuts");
    auto group_shortcuts_advancedName = QObject::tr("Advanced");
    auto group_shortcuts_terminalName = QObject::tr("Terminal");
    auto group_shortcuts_workspaceName = QObject::tr("Workspace");
    auto shortcuts_advanced_fullscreenName = QObject::tr("Fullscreen");
    auto shortcuts_advanced_rename_tabName = QObject::tr("Rename tab");
    auto shortcuts_terminal_copyName = QObject::tr("Copy");
    auto shortcuts_terminal_pasteName = QObject::tr("Paste");
    auto shortcuts_terminal_zoom_inName = QObject::tr("Zoom in");
    auto shortcuts_terminal_zoom_outName = QObject::tr("Zoom out");
    auto shortcuts_workspace_focus_nav_downName = QObject::tr("Select lower window");
    auto shortcuts_workspace_focus_nav_leftName = QObject::tr("Select left window");
    auto shortcuts_workspace_focus_nav_rightName = QObject::tr("Select right window");
    auto shortcuts_workspace_focus_nav_upName = QObject::tr("Select upper window");
    auto shortcuts_workspace_horizontal_splitName = QObject::tr("Horizontal split");
    auto shortcuts_workspace_new_tabName = QObject::tr("New tab");
    auto shortcuts_workspace_vertical_splitName = QObject::tr("Vertical split");
}
