.\"                                      Hey, EMACS: -*- nroff -*-
.\" (C) Copyright 2021 hufeng <hufeng@uniontech.com>,
.\"
.TH "deepin-terminal" "1" "2021-1-28" "Deepin"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
deepin-terminal \- an advanced terminal emulator for deepin.
.SH SYNOPSIS
.PP
\fBdeepin-terminal\fR [\fB-v, \-\-version\fP] [\fB-w, \-\-work-directory \f\<path\>\fR\fP] [\fB\-e, \-\-execute \f\<command\>\fR\fP] [\fB-q, \-\-quake-mode\fP] [\fB\-m, \-\-window-mode \f\<state-mode\>\fR\fP] [\fB\-\-keep-open\fP] [\fB-C, \-\-run-script \f\<script\>\fR\fP] [\fB\-h, \-\-help\fP]
.SH DESCRIPTION
Terminal is a terminal emulator with simple interface, rich and powerful functions such as multi-windows, workspace, remote management, Quake mode and etc. You can instantly start and close Terminal smoothly like normal file window, allowing you to input commands with facility and no distractions.
.SH OPTIONS
.IP "\fB\-v, \-\-version\fP" 10
Display version.
.IP "\fB\-w, \-\-work-directory \f\<path\>\fR\fP" 10
Set the work directory of the terminal.
.IP "\fB\-e, \-\-execute \f\<command\>\fR\fP" 10
Execute a command in the terminal.
.IP "\fB-q, \-\-quake-mode\fP" 10
Run terminal in quake mode.
.IP "\fB\-m, \-\-window-mode \f\<state-mode\>\fR\fP" 10
Set the window mode on starting, window mode options are normal, maximum, fullscreen and splitscreen.
.IP "\fB\-\-keep-open\fP" 10
Keep terminal open when command finishes.
.IP "\fB-C, \-\-run-script \f\<script\>\fR\fP" 10
Run script string in the terminal.
.IP "\fB\-h, \-\-help\fP" 10
Show help message.
.SH SEE ALSO
https://github.com/linuxdeepin/deepin-terminal
.SH AUTHOR
.PP
.B deepin-terminal
is written by Deepin Technology Co., Ltd.
.PP
This manual page was written by
.MT wangliang@\:uniontech.com
Wang Liang
.ME
for the Debian Project (but may be used by others)
