// This file was generated by dtk-settings-tools version 0.1.2

#include <DSettings>

void GenerateSettingTranslate()
{
    auto advanced_cursor_auto_copy_selectionText = QObject::tr("Copy on select");
//    auto advanced_cursor_auto_hideText = QObject::tr("Cursor autohide");
    auto advanced_cursor_cursor_blinkText = QObject::tr("Cursor blink");
    auto advanced_cursor_cursor_shapeName = QObject::tr("Cursor style");
    auto advanced_scroll_scroll_on_keyText = QObject::tr("Scroll on keystroke");
    auto advanced_scroll_scroll_on_outputText = QObject::tr("Scroll on output");
    auto advanced_window_auto_hide_raytheon_windowText = QObject::tr("Hide Quake window after losing focus");
    auto advanced_window_blurred_backgroundText = QObject::tr("Blur background");
    auto advanced_window_use_on_startingName = QObject::tr("Use on starting");
    auto basic_interface_fontName = QObject::tr("Font");
    auto basic_interface_font_sizeName = QObject::tr("Font size");
    auto basic_interface_opacityName = QObject::tr("Opacity");
    auto group_advancedName = QObject::tr("Advanced");
    auto group_advanced_cursorName = QObject::tr("Cursor");
    auto group_advanced_scrollName = QObject::tr("Scroll");
    auto group_advanced_windowName = QObject::tr("Window");
    auto group_basicName = QObject::tr("Basic");
    auto group_basic_interfaceName = QObject::tr("Interface");
    auto group_shortcutsName = QObject::tr("Shortcuts");
    auto group_shortcuts_advancedName = QObject::tr("Advanced");
    auto group_shortcuts_terminalName = QObject::tr("Terminal");
    auto group_shortcuts_workspaceName = QObject::tr("Workspace");
    auto shortcuts_advanced_custom_commandName = QObject::tr("Custom commands");
    auto shortcuts_advanced_display_shortcutsName = QObject::tr("Display shortcuts");
    auto shortcuts_advanced_remote_managementName = QObject::tr("Remote management");
    auto shortcuts_advanced_rename_tabName = QObject::tr("Rename title");
    auto shortcuts_advanced_switch_fullscreenName = QObject::tr("Fullscreen");
    auto shortcuts_terminal_copyName = QObject::tr("Copy");
    auto shortcuts_terminal_default_sizeName = QObject::tr("Default size");
    auto shortcuts_terminal_pasteName = QObject::tr("Paste");
    auto shortcuts_terminal_searchName = QObject::tr("Search");
    auto shortcuts_terminal_select_allName = QObject::tr("Select all");
    auto shortcuts_terminal_skip_to_next_commandName = QObject::tr("Jump to next command");
    auto shortcuts_terminal_skip_to_previous_commandName = QObject::tr("Jump to previous command");
    auto shortcuts_terminal_zoom_inName = QObject::tr("Zoom in");
    auto shortcuts_terminal_zoom_outName = QObject::tr("Zoom out");
    auto shortcuts_workspace_close_other_windowsName = QObject::tr("Close other windows");
    auto shortcuts_workspace_close_other_workspace = QObject::tr("Close other workspace");
    auto shortcuts_workspace_close_windowName = QObject::tr("Close window");
    auto shortcuts_workspace_close_workspaceName = QObject::tr("Close workspace");
    auto shortcuts_workspace_horionzal_splitName = QObject::tr("Horizontal split");
    auto shortcuts_workspace_new_workspaceName = QObject::tr("New workspace");
    auto shortcuts_workspace_next_workspaceName = QObject::tr("Next workspace");
    auto shortcuts_workspace_previous_workspaceName = QObject::tr("Previous workspace");
    auto shortcuts_workspace_select_left_windowName = QObject::tr("Select left window");
    auto shortcuts_workspace_select_lower_windowName = QObject::tr("Select lower window");
    auto shortcuts_workspace_select_right_windowName = QObject::tr("Select right window");
    auto shortcuts_workspace_select_upper_windowName = QObject::tr("Select upper window");
    auto shortcuts_workspace_vertical_splitName = QObject::tr("Vertical split");
    auto shortcuts_terminal_FindName = QObject::tr("Find");
}
