/*
 *  Copyright (C) 2019 ~ 2020 Uniontech Software Technology Co.,Ltd
 *
 * Author:     zhangmeng <zhangmeng@uniontech.com>
 *
 * Maintainer: zhangmeng <zhangmeng@uniontech.com>
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
// This file was generated by dtk-settings-tools version 0.1.2

#include <DSettings>

void GenerateSettingTranslate()
{
    auto advanced_cursor_auto_copy_selectionText = QObject::tr("Copy on select");
    Q_UNUSED(advanced_cursor_auto_copy_selectionText);
//    auto advanced_cursor_auto_hideText = QObject::tr("Cursor autohide");
    auto advanced_cursor_cursor_blinkText = QObject::tr("Cursor blink");
    Q_UNUSED(advanced_cursor_cursor_blinkText);
    auto advanced_cursor_cursor_shapeName = QObject::tr("Cursor style");
    Q_UNUSED(advanced_cursor_cursor_shapeName);
    auto advanced_scroll_scroll_on_keyText = QObject::tr("Scroll on keystroke");
    Q_UNUSED(advanced_scroll_scroll_on_keyText);
    auto advanced_scroll_scroll_on_outputText = QObject::tr("Scroll on output");
    Q_UNUSED(advanced_scroll_scroll_on_outputText);
    auto advanced_window_auto_hide_raytheon_windowText = QObject::tr("Hide Quake window after losing focus");
    Q_UNUSED(advanced_window_auto_hide_raytheon_windowText);
    auto advanced_window_blurred_backgroundText = QObject::tr("Blur background");
    Q_UNUSED(advanced_window_blurred_backgroundText);
    auto advanced_window_use_on_startingName = QObject::tr("Use on starting");
    Q_UNUSED(advanced_window_use_on_startingName);
    auto basic_interface_fontName = QObject::tr("Font");
    Q_UNUSED(basic_interface_fontName);
    auto basic_interface_font_sizeName = QObject::tr("Font size");
    Q_UNUSED(basic_interface_font_sizeName);
    auto basic_interface_opacityName = QObject::tr("Opacity");
    Q_UNUSED(basic_interface_opacityName);
    auto group_advancedName = QObject::tr("Advanced");
    Q_UNUSED(group_advancedName);
    auto group_advanced_cursorName = QObject::tr("Cursor");
    Q_UNUSED(group_advanced_cursorName);
    auto group_advanced_scrollName = QObject::tr("Scroll");
    Q_UNUSED(group_advanced_scrollName);
    auto group_advanced_windowName = QObject::tr("Window");
    Q_UNUSED(group_advanced_windowName);
    auto group_basicName = QObject::tr("Basic");
    Q_UNUSED(group_basicName);
    auto group_basic_interfaceName = QObject::tr("Interface");
    Q_UNUSED(group_basic_interfaceName);
    auto group_shortcutsName = QObject::tr("Shortcuts");
    Q_UNUSED(group_shortcutsName);
    auto group_shortcuts_advancedName = QObject::tr("Others");
    Q_UNUSED(group_shortcuts_advancedName);
    auto group_shortcuts_terminalName = QObject::tr("Terminal");
    Q_UNUSED(group_shortcuts_terminalName);
    auto group_shortcuts_workspaceName = QObject::tr("Workspace");
    Q_UNUSED(group_shortcuts_workspaceName);
    auto shortcuts_advanced_custom_commandName = QObject::tr("Custom commands");
    Q_UNUSED(shortcuts_advanced_custom_commandName);
    auto shortcuts_advanced_display_shortcutsName = QObject::tr("Display shortcuts");
    Q_UNUSED(shortcuts_advanced_display_shortcutsName);
    auto shortcuts_advanced_remote_managementName = QObject::tr("Remote management");
    Q_UNUSED(shortcuts_advanced_remote_managementName);
    auto shortcuts_advanced_rename_tabName = QObject::tr("Rename title");
    Q_UNUSED(shortcuts_advanced_rename_tabName);
    auto shortcuts_advanced_switch_fullscreenName = QObject::tr("Fullscreen");
    Q_UNUSED(shortcuts_advanced_switch_fullscreenName);
    auto shortcuts_terminal_copyName = QObject::tr("Copy");
    Q_UNUSED(shortcuts_terminal_copyName);
    auto shortcuts_terminal_default_sizeName = QObject::tr("Default size");
    Q_UNUSED(shortcuts_terminal_default_sizeName);
    auto shortcuts_terminal_pasteName = QObject::tr("Paste");
    Q_UNUSED(shortcuts_terminal_pasteName);
    auto shortcuts_terminal_searchName = QObject::tr("Search");
    Q_UNUSED(shortcuts_terminal_searchName);
    auto shortcuts_terminal_select_allName = QObject::tr("Select all");
    Q_UNUSED(shortcuts_terminal_select_allName);
    auto shortcuts_terminal_skip_to_next_commandName = QObject::tr("Jump to next command");
    Q_UNUSED(shortcuts_terminal_skip_to_next_commandName);
    auto shortcuts_terminal_skip_to_previous_commandName = QObject::tr("Jump to previous command");
    Q_UNUSED(shortcuts_terminal_skip_to_previous_commandName);
    auto shortcuts_terminal_zoom_inName = QObject::tr("Zoom in");
    Q_UNUSED(shortcuts_terminal_zoom_inName);
    auto shortcuts_terminal_zoom_outName = QObject::tr("Zoom out");
    Q_UNUSED(shortcuts_terminal_zoom_outName);
    auto shortcuts_workspace_close_other_windowsName = QObject::tr("Close other windows");
    Q_UNUSED(shortcuts_workspace_close_other_windowsName);
    auto shortcuts_workspace_close_other_workspace = QObject::tr("Close other workspaces");
    Q_UNUSED(shortcuts_workspace_close_other_workspace);
    auto shortcuts_workspace_close_windowName = QObject::tr("Close window");
    Q_UNUSED(shortcuts_workspace_close_windowName);
    auto shortcuts_workspace_close_workspaceName = QObject::tr("Close workspace");
    Q_UNUSED(shortcuts_workspace_close_workspaceName);
    auto shortcuts_workspace_horionzal_splitName = QObject::tr("Horizontal split");
    Q_UNUSED(shortcuts_workspace_horionzal_splitName);
    auto shortcuts_workspace_new_workspaceName = QObject::tr("New workspace");
    Q_UNUSED(shortcuts_workspace_new_workspaceName);
    auto shortcuts_workspace_next_workspaceName = QObject::tr("Next workspace");
    Q_UNUSED(shortcuts_workspace_next_workspaceName);
    auto shortcuts_workspace_previous_workspaceName = QObject::tr("Previous workspace");
    Q_UNUSED(shortcuts_workspace_previous_workspaceName);
    auto shortcuts_workspace_select_left_windowName = QObject::tr("Select left window");
    Q_UNUSED(shortcuts_workspace_select_left_windowName);
    auto shortcuts_workspace_select_lower_windowName = QObject::tr("Select lower window");
    Q_UNUSED(shortcuts_workspace_select_lower_windowName);
    auto shortcuts_workspace_select_right_windowName = QObject::tr("Select right window");
    Q_UNUSED(shortcuts_workspace_select_right_windowName);
    auto shortcuts_workspace_select_upper_windowName = QObject::tr("Select upper window");
    Q_UNUSED(shortcuts_workspace_select_upper_windowName);
    auto shortcuts_workspace_vertical_splitName = QObject::tr("Vertical split");
    Q_UNUSED(shortcuts_workspace_vertical_splitName);
    auto shortcuts_terminal_FindName = QObject::tr("Find");
    Q_UNUSED(shortcuts_terminal_FindName);
}
