
#ifndef UT_DEFINES_TEST_H
#define UT_DEFINES_TEST_H

//是否开启UI测试
#define ENABLE_UI_TEST

#define UT_UTILS_TEST

#define UT_CUSTOMCOMMANDPANEL_TEST
#define UT_CUSTOMCOMMANDOPTDLG_TEST

#define UT_ENCODELISTVIEW_TEST
#define UT_ENCODEPANEL_TEST

#define UT_MAINWINDOW_TEST
#define UT_SERVICE_TEST

#define UT_REMOTEMANAGEMENTPANEL_TEST
#define UT_SERVERCONFIGOPTDLG_TEST

#define UT_SETTINGS_TEST

#define UT_THEMELISTVIEW_TEST
#define UT_THEMEPANEL_TEST

#define UT_LISTVIEW_TEST
#define UT_TABBAR_TEST

#define UT_DBUSMANAGER_TEST

#define UT_TERMWIDGETPAGE_TEST
#define UT_TERMWIDGET_TEST
#define UT_TITLEBAR_TEST
#define UT_PAGESEARCHBAR_TEST

#endif // UT_DEFINES_TEST_H

